/**
 * Tiny procedural sound effects, synthesised at runtime with the Web Audio
 * API. There are no audio files and no third-party samples — every cue is
 * generated by the code below, so there is nothing to license (see ASSETS.md).
 *
 * Browsers create an AudioContext in a *suspended* state until a user gesture,
 * so {@link unlock} must be called from a pointer/key handler before sound
 * will play. A single shared instance ({@link sfx}) is used so the game keeps
 * one AudioContext across scene restarts instead of leaking a new one each time.
 */
export class Sfx {
  constructor() {
    /** @type {AudioContext|null} Created lazily on first {@link unlock}. */
    this._ctx = null;
    /** @type {GainNode|null} Master bus, so the whole mix is tamed in one spot. */
    this._master = null;
    /** @type {AudioBuffer|null} Cached short white-noise used by the click. */
    this._noise = null;
    /** @type {Object|null} Live nodes of the stretching-band sound, or null. */
    this._band = null;
    /** Flip to false to silence the game. */
    this.enabled = true;
  }

  /**
   * Create the AudioContext (first call) and resume it. Must be triggered by a
   * user gesture the first time or the browser keeps it suspended. Idempotent.
   *
   * @returns {void}
   */
  unlock() {
    if (!this.enabled) return;
    if (!this._ctx) {
      const AC = window.AudioContext || window.webkitAudioContext;
      if (!AC) {
        this.enabled = false; // no Web Audio here; fail quietly
        return;
      }
      this._ctx = new AC();
      this._master = this._ctx.createGain();
      this._master.gain.value = 0.5;
      this._master.connect(this._ctx.destination);
    }
    if (this._ctx.state === 'suspended') this._ctx.resume();
  }

  /**
   * Release the audio thread when the page is hidden, so it costs no CPU in a
   * background tab. Any held band is stopped first so nothing resumes stuck.
   *
   * @returns {void}
   */
  suspend() {
    if (this._ctx && this._ctx.state === 'running') {
      this.stopBand();
      this._ctx.suspend();
    }
  }

  /**
   * Resume audio when the page becomes visible again. Only un-suspends a
   * context that exists and was previously started (never forces a new one).
   *
   * @returns {void}
   */
  resume() {
    if (this._ctx && this._ctx.state === 'suspended') this._ctx.resume();
  }

  /**
   * A short pitched blip with a fast percussive envelope.
   *
   * @param {{freq:number, dur:number, gain?:number, type?:OscillatorType,
   *   glideTo?:number, at?:number, destination?:AudioNode}} o
   * @returns {void}
   */
  _blip(o) {
    const ctx = /** @type {AudioContext} */ (this._ctx);
    const t = o.at ?? ctx.currentTime;
    const osc = ctx.createOscillator();
    const g = ctx.createGain();
    osc.type = o.type ?? 'sine';
    osc.frequency.setValueAtTime(o.freq, t);
    if (o.glideTo) osc.frequency.exponentialRampToValueAtTime(o.glideTo, t + o.dur);
    const peak = o.gain ?? 0.3;
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(peak, t + 0.012);
    g.gain.exponentialRampToValueAtTime(0.0001, t + o.dur);
    osc.connect(g).connect(o.destination ?? /** @type {GainNode} */ (this._master));
    osc.start(t);
    osc.stop(t + o.dur + 0.02);
  }

  /**
   * Billiard-style "click": a short white-noise burst through a bandpass with
   * a very fast decay, plus a brief tonal knock for body. Slight random pitch
   * so repeated hits don't sound mechanical.
   *
   * @returns {void}
   */
  hit() {
    if (!this._ctx) return;
    const ctx = this._ctx;
    const t = ctx.currentTime;
    const dur = 0.06;

    if (!this._noise) {
      const len = Math.ceil(ctx.sampleRate * 0.1);
      this._noise = ctx.createBuffer(1, len, ctx.sampleRate);
      const data = this._noise.getChannelData(0);
      for (let i = 0; i < len; i++) data[i] = Math.random() * 2 - 1;
    }
    const src = ctx.createBufferSource();
    src.buffer = this._noise;
    const bp = ctx.createBiquadFilter();
    bp.type = 'bandpass';
    bp.frequency.value = 2600;
    bp.Q.value = 1.2;
    const g = ctx.createGain();
    g.gain.setValueAtTime(0.7, t);
    g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
    src.connect(bp).connect(g).connect(/** @type {GainNode} */ (this._master));
    src.start(t);
    src.stop(t + dur);

    this._blip({ freq: 300 + Math.random() * 80, type: 'triangle', dur: 0.05, gain: 0.22, at: t });
  }

  /**
   * Teleport: a quick upward pitch sweep ("vwoop") — the classic warp cue. A
   * triangle lead with a sine an octave below for body, both gliding up fast.
   *
   * @returns {void}
   */
  teleport() {
    if (!this._ctx) return;
    const t = this._ctx.currentTime;
    this._blip({ freq: 180, glideTo: 1500, dur: 0.26, type: 'triangle', gain: 0.3, at: t });
    this._blip({ freq: 90, glideTo: 750, dur: 0.26, type: 'sine', gain: 0.16, at: t });
  }

  /**
   * Success: a quick rising major arpeggio (C5–E5–G5–C6) with a sparkle on
   * top — a bright, triumphant flourish.
   *
   * @returns {void}
   */
  win() {
    if (!this._ctx) return;
    const t = this._ctx.currentTime;
    const notes = [523.25, 659.25, 783.99, 1046.5];
    notes.forEach((f, i) =>
      this._blip({ freq: f, type: 'triangle', dur: 0.5 - i * 0.04, gain: 0.3, at: t + i * 0.11 })
    );
    this._blip({ freq: 1568, type: 'sine', dur: 0.4, gain: 0.14, at: t + 0.33 });
  }

  /**
   * Failure: two soft, lowpass-filtered tones bending downward — a sad little
   * "wah-wah" that reads as "awww".
   *
   * @returns {void}
   */
  lose() {
    if (!this._ctx) return;
    const t = this._ctx.currentTime;
    this._wah(220, 165, t, 0.32);
    this._wah(175, 110, t + 0.3, 0.5);
  }

  /**
   * Begin the "stretching rubber band" sound, held until {@link stopBand}. A
   * cartoon-rubber FM voice (see rubber-band-simulator.html): a triangle
   * *carrier* (hollow, elastic body) is frequency-modulated by a detuned
   * sawtooth *modulator* for rubbery grit, then shaped by a resonant lowpass —
   * the hollow "balloon squelch". Both oscillators run continuously but the
   * output starts silent; {@link updateBand} drives pitch from tension and
   * volume from how fast the draw length is changing, so a held stretch falls
   * silent and can never hum. No-op if audio isn't unlocked yet or a band is
   * already playing.
   *
   * @returns {void}
   */
  startBand() {
    if (!this._ctx || this._band) return;
    const ctx = this._ctx;
    const master = /** @type {GainNode} */ (this._master);

    // Carrier: the primary tone. Triangle reads as a hollow, elastic texture.
    const carrier = ctx.createOscillator();
    carrier.type = 'triangle';
    // Modulator: a sawtooth driving the carrier's frequency (FM) to inject the
    // chaotic, "rubbery" friction artefacts. Detuned by modRatio in updateBand.
    const modulator = ctx.createOscillator();
    modulator.type = 'sawtooth';
    const modGain = ctx.createGain(); // FM depth (squeak intensity)
    // Resonant lowpass: the hollow cavity of a balloon shell.
    const filter = ctx.createBiquadFilter();
    filter.type = 'lowpass';
    // Motion gate: gain follows how fast the length is changing (set per frame
    // in updateBand). Starts at silence.
    const g = ctx.createGain();
    g.gain.value = 0.0001;

    // Modulator -> modGain -> carrier.frequency; carrier -> filter -> gate -> out.
    modulator.connect(modGain);
    modGain.connect(carrier.frequency);
    carrier.connect(filter);
    filter.connect(g);
    g.connect(master);

    carrier.start();
    modulator.start();

    this._band = { carrier, modulator, modGain, filter, g, lastK: 0, lastT: ctx.currentTime };
  }

  /**
   * Drive the rubber-band FM voice from the *current* draw tension. Call this
   * every frame while aiming (not only when the pointer moves), so a held draw
   * decays to silence. Pitch (and FM depth / filter brightness) rise with
   * tension; loudness tracks the rate of length change — it only makes noise
   * while stretching or relaxing. No-op if no band is playing.
   *
   * @param {number} tension  0 (slack) .. 1 (fully drawn).
   * @returns {void}
   */
  updateBand(tension) {
    if (!this._band || !this._ctx) return;
    const k = Math.max(0, Math.min(1, tension));
    const now = this._ctx.currentTime;
    const b = this._band;
    const ramp = (param, v, tc = 0.02) => param.setTargetAtTime(v, now, tc);

    // Rate of length change since the last frame; only this makes sound.
    const dt = Math.max(1e-3, now - b.lastT);
    const activity = Math.min(1, (Math.abs(k - b.lastK) / dt) * 0.35);
    b.lastK = k;
    b.lastT = now;

    // Synth parameters mirror the reference simulator. Tension stands in for the
    // simulator's pull distance via a nominal stretch span, so the same pitch /
    // FM-depth math applies. (basePitch 85, pitchBend 2.5, modRatio 1.4,
    // modScale 10, filterQ 1.)
    const stretch = k * 280; // nominal pull distance in "px"
    const pitch = 85 + stretch * 2.5; // ~85..785 Hz as tension rises
    const modDepth = stretch * (10 / 100) * (pitch * 0.1); // FM depth (grit)

    ramp(b.carrier.frequency, pitch);
    ramp(b.modulator.frequency, pitch * 1.4);
    ramp(b.modGain.gain, modDepth);
    ramp(b.filter.frequency, pitch * 2.5, 0.03); // brighter as it scales out
    ramp(b.filter.Q, 1);
    // Velocity -> amplitude. Capped so fast yanks don't blow out the mix.
    ramp(b.g.gain, Math.min(0.21, activity * 0.4), 0.01);
  }

  /**
   * Stop the rubber-band sound with a short fade so a release doesn't click.
   *
   * @returns {void}
   */
  stopBand() {
    if (!this._band || !this._ctx) return;
    const b = this._band;
    const now = this._ctx.currentTime;
    b.g.gain.cancelScheduledValues(now);
    b.g.gain.setTargetAtTime(0.0001, now, 0.03);
    b.carrier.stop(now + 0.15);
    b.modulator.stop(now + 0.15);
    this._band = null;
  }

  /**
   * One downward-gliding, lowpass-softened "wah" tone for {@link lose}.
   *
   * @param {number} from  Start frequency (Hz).
   * @param {number} to    End frequency (Hz).
   * @param {number} at    Start time (AudioContext seconds).
   * @param {number} dur   Duration (s).
   * @returns {void}
   */
  _wah(from, to, at, dur) {
    const ctx = /** @type {AudioContext} */ (this._ctx);
    const osc = ctx.createOscillator();
    const lp = ctx.createBiquadFilter();
    const g = ctx.createGain();
    lp.type = 'lowpass';
    lp.frequency.value = 900;
    osc.type = 'sawtooth';
    osc.frequency.setValueAtTime(from, at);
    osc.frequency.exponentialRampToValueAtTime(to, at + dur);
    g.gain.setValueAtTime(0.0001, at);
    g.gain.exponentialRampToValueAtTime(0.3, at + 0.05);
    g.gain.exponentialRampToValueAtTime(0.0001, at + dur);
    osc.connect(lp).connect(g).connect(/** @type {GainNode} */ (this._master));
    osc.start(at);
    osc.stop(at + dur + 0.02);
  }
}

/** Shared instance: one AudioContext for the whole game, reused across restarts. */
export const sfx = new Sfx();
