/**
 * Tiny procedural sound effects, synthesised at runtime with the Web Audio API.
 * Almost every cue is generated by the code below, so there is nothing to
 * license. The one exception is {@link oof}, which plays from a recorded (CC0)
 * voice sprite — see ASSETS.md for its provenance.
 *
 * Browsers create an AudioContext in a *suspended* state until a user gesture,
 * so {@link unlock} must be called from a pointer/key handler before sound
 * will play. A single shared instance ({@link sfx}) is used so the game keeps
 * one AudioContext across scene restarts instead of leaking a new one each time.
 */
import { OOF_SPRITE_URL, OOF_CLIPS } from './oofs.js';
import { Config } from './config.js';
import * as diag from './diag.js';

export class Sfx {
  constructor() {
    /** @type {AudioContext|null} Created lazily on first {@link unlock}. */
    this._ctx = null;
    /** @type {GainNode|null} Master bus, so the whole mix is tamed in one spot. */
    this._master = null;
    /** @type {AudioBuffer|null} Cached short white-noise used by the click. */
    this._noise = null;
    /** @type {AudioBuffer|null} Cached longer white-noise used by the explosion. */
    this._boomNoise = null;
    /** @type {Object|null} Live nodes of the stretching-band sound, or null. */
    this._band = null;
    /** @type {AudioBuffer|null} The decoded "oof" voice sprite; null until loaded. */
    this._oofs = null;
    /** True while the sprite fetch/decode is in flight, so we only do it once. */
    this._oofsPending = false;
    /** Index of the last oof played, so the same grunt never repeats back-to-back. */
    this._lastOof = -1;
    /** AudioContext time of the last oof, for the retrigger guard in {@link oof}. */
    this._lastOofAt = -1;
    /** True once {@link _warmup} has run, so it only does so once. */
    this._warmed = false;
    /** True once {@link primeBand} has warmed the band's audible DSP path. */
    this._bandPrimed = false;
    /** Flip to false to silence the game. */
    this.enabled = true;
  }

  /**
   * Create the AudioContext (first call) and resume it. Must be triggered by a
   * user gesture the first time or the browser keeps it suspended. Idempotent.
   *
   * @returns {void}
   */
  unlock() {
    if (!this.enabled) return;
    if (!this._ctx) {
      const AC = window.AudioContext || window.webkitAudioContext;
      if (!AC) {
        this.enabled = false; // no Web Audio here; fail quietly
        return;
      }
      this._ctx = new AC();
      this._master = this._ctx.createGain();
      this._master.gain.value = 0.5;
      this._master.connect(this._ctx.destination);
    }
    if (this._ctx.state === 'suspended') this._ctx.resume();
    this._warmup();
    this._loadOofs(); // fire-and-forget; oof() stays silent until it lands
  }

  /**
   * Fetch and decode the "oof" voice sprite into a single AudioBuffer. Kicked
   * off (once) from {@link unlock}, because decodeAudioData needs the context
   * that unlock creates. Deliberately not awaited: the game must not stall on
   * it, and {@link oof} simply no-ops until the buffer is here.
   *
   * All 23 grunts live in ONE file and are played as sub-regions of this one
   * buffer (see `oofs.js`), so this is a single request and a single decode.
   *
   * @returns {Promise<void>}
   */
  async _loadOofs() {
    if (this._oofs || this._oofsPending || !this._ctx) return;
    this._oofsPending = true;
    try {
      const res = await fetch(OOF_SPRITE_URL);
      if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
      this._oofs = await this._ctx.decodeAudioData(await res.arrayBuffer());
      diag.breadcrumb('sfx: oof sprite loaded', { clips: OOF_CLIPS.length });
    } catch (e) {
      // A missing or undecodable sprite must not take the rest of the sound
      // down with it — every other cue is synthesised and still works.
      diag.error('sfx: could not load oof sprite', e);
    } finally {
      this._oofsPending = false;
    }
  }

  /**
   * On the unlocking gesture, bring the hardware output stream up (a brief silent
   * buffer) and build the persistent band graph now, while nothing else is
   * playing. Building it later — as the title band first sounds over the music —
   * would modify the audio graph mid-playback, which glitches the music on the
   * audio thread (the whole point of {@link _ensureBand}). Runs once.
   *
   * @returns {void}
   */
  _warmup() {
    if (!this._ctx || this._warmed) return;
    this._warmed = true;
    const ctx = this._ctx;
    const t = ctx.currentTime;
    const dur = 0.06;

    // Silent buffer: brings the hardware output stream up.
    const bs = ctx.createBufferSource();
    bs.buffer = ctx.createBuffer(1, Math.max(1, Math.round(dur * ctx.sampleRate)), ctx.sampleRate);
    bs.connect(ctx.destination);
    bs.start(t);
    bs.stop(t + dur);

    this._ensureBand();
  }

  /**
   * Warm the band's *audible* DSP path once: the first time this FM+lowpass
   * subgraph actually produces output the engine initializes it — a one-time
   * hitch that underruns concurrent audio (the first-arc click). Drive it briefly
   * here, at a low level, so the first real stretch reuses the warmed path.
   *
   * Calls `onDone` once the warm has finished PLAYING — signalled by a silent
   * timer source's `onended`, i.e. on the audio clock, not a fragile fixed delay —
   * so a caller can start other audio strictly after it (the music). Must run with
   * the context RUNNING (else scheduled events don't process and nothing
   * initializes), so callers invoke it as the music starts, not at the unlocking
   * gesture, which on mobile may not have resumed the context yet.
   *
   * @param {() => void} onDone  Called (once) after the warm finishes.
   * @returns {boolean} true if a warm was started (and `onDone` will fire);
   *   false if it can't warm now or already has — the caller should proceed itself.
   */
  primeBand(onDone) {
    if (!this._ctx || this._ctx.state !== 'running' || this._bandPrimed) return false;
    this._ensureBand();
    const b = this._band;
    if (!b) return false;
    this._bandPrimed = true;

    const ctx = this._ctx;
    const t = ctx.currentTime;
    // A brief but REAL stretch: sweep the FM depth and the moving lowpass across
    // their operating range (as updateBand does over a real pull), at an audible
    // level, so the exact DSP path the arc uses actually initializes. A static,
    // low-level tone (what we had) doesn't init it — the click came back.
    const tc = 0.015; // automation time-constant, ~like updateBand
    b.carrier.frequency.setValueAtTime(85, t);
    b.carrier.frequency.setTargetAtTime(785, t, tc); // 85 -> ~785 Hz
    b.modulator.frequency.setValueAtTime(120, t);
    b.modulator.frequency.setTargetAtTime(1100, t, tc);
    b.modGain.gain.setValueAtTime(1, t);
    b.modGain.gain.setTargetAtTime(2200, t, tc); // full FM depth
    b.filter.frequency.setValueAtTime(212, t);
    b.filter.frequency.setTargetAtTime(1960, t, tc); // full filter sweep
    b.filter.Q.setValueAtTime(1, t);
    b.g.gain.setValueAtTime(0.0001, t);
    b.g.gain.setTargetAtTime(0.16, t, 0.01); // rise to near a real stretch's level
    b.g.gain.setTargetAtTime(0.0001, t + 0.06, 0.015); // then fall back to silence

    // Silent timer: its onended fires once the warm has played through, so the
    // caller starts the music strictly after it (no fixed-delay guess).
    const timer = ctx.createBufferSource();
    timer.buffer = ctx.createBuffer(1, Math.max(1, Math.round(0.2 * ctx.sampleRate)), ctx.sampleRate);
    timer.connect(ctx.destination);
    timer.onended = () => onDone();
    timer.start(t);
    timer.stop(t + 0.2);
    return true;
  }

  /**
   * Build the stretching-band voice ONCE and leave it connected and running,
   * silent, forever. {@link startBand}/{@link stopBand} then only gate its gain —
   * they never add or remove nodes. This is what stops the first band from
   * glitching concurrent audio (e.g. the title music): connecting nodes to a
   * live graph forces a re-plan that hiccups whatever is already playing, and
   * that first structural change was the click at David's opening arc.
   *
   * @returns {void}
   */
  _ensureBand() {
    if (!this._ctx || this._band) return;
    const ctx = this._ctx;
    const master = /** @type {GainNode} */ (this._master);

    const carrier = ctx.createOscillator(); // hollow, elastic body
    carrier.type = 'triangle';
    const modulator = ctx.createOscillator(); // FM grit
    modulator.type = 'sawtooth';
    const modGain = ctx.createGain(); // FM depth
    const filter = ctx.createBiquadFilter(); // resonant lowpass "balloon squelch"
    filter.type = 'lowpass';
    const g = ctx.createGain(); // motion gate; silent until active
    g.gain.value = 0.0001;

    modulator.connect(modGain);
    modGain.connect(carrier.frequency);
    carrier.connect(filter);
    filter.connect(g);
    g.connect(master);
    carrier.start();
    modulator.start();

    this._band = { carrier, modulator, modGain, filter, g, lastK: 0, lastT: ctx.currentTime, active: false };
  }

  /**
   * Release the audio thread when the page is hidden, so it costs no CPU in a
   * background tab. Any held band is stopped first so nothing resumes stuck.
   *
   * @returns {void}
   */
  suspend() {
    if (this._ctx && this._ctx.state === 'running') {
      this.stopBand();
      this._ctx.suspend();
    }
  }

  /**
   * Resume audio when the page becomes visible again. Only un-suspends a
   * context that exists and was previously started (never forces a new one).
   *
   * @returns {void}
   */
  resume() {
    if (this._ctx && this._ctx.state === 'suspended') this._ctx.resume();
  }

  /**
   * The shared AudioContext, once {@link unlock} has created it (else `null`).
   * Exposed so other audio (the title music) can play through the SAME context
   * and output stream: with a second context, the first time the SFX produces
   * sound the OS spins up another output stream and hiccups whatever is already
   * playing (once). Sharing one context avoids that.
   *
   * @returns {AudioContext|null}
   */
  get context() {
    return this._ctx;
  }

  /**
   * A short pitched blip with a fast percussive envelope.
   *
   * @param {{freq:number, dur:number, gain?:number, type?:OscillatorType,
   *   glideTo?:number, at?:number, destination?:AudioNode}} o
   * @returns {void}
   */
  _blip(o) {
    const ctx = /** @type {AudioContext} */ (this._ctx);
    const t = o.at ?? ctx.currentTime;
    const osc = ctx.createOscillator();
    const g = ctx.createGain();
    osc.type = o.type ?? 'sine';
    osc.frequency.setValueAtTime(o.freq, t);
    if (o.glideTo) osc.frequency.exponentialRampToValueAtTime(o.glideTo, t + o.dur);
    const peak = o.gain ?? 0.3;
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(peak, t + 0.012);
    g.gain.exponentialRampToValueAtTime(0.0001, t + o.dur);
    osc.connect(g).connect(o.destination ?? /** @type {GainNode} */ (this._master));
    osc.start(t);
    osc.stop(t + o.dur + 0.02);
  }

  /**
   * Billiard-style "click": a short white-noise burst through a bandpass with
   * a very fast decay, plus a brief tonal knock for body. Slight random pitch
   * so repeated hits don't sound mechanical.
   *
   * @returns {void}
   */
  hit() {
    if (!this._ctx) return;
    const ctx = this._ctx;
    const t = ctx.currentTime;
    const dur = 0.06;

    if (!this._noise) {
      const len = Math.ceil(ctx.sampleRate * 0.1);
      this._noise = ctx.createBuffer(1, len, ctx.sampleRate);
      const data = this._noise.getChannelData(0);
      for (let i = 0; i < len; i++) data[i] = Math.random() * 2 - 1;
    }
    const src = ctx.createBufferSource();
    src.buffer = this._noise;
    const bp = ctx.createBiquadFilter();
    bp.type = 'bandpass';
    bp.frequency.value = 2600;
    bp.Q.value = 1.2;
    const g = ctx.createGain();
    g.gain.setValueAtTime(0.7, t);
    g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
    src.connect(bp).connect(g).connect(/** @type {GainNode} */ (this._master));
    src.start(t);
    src.stop(t + dur);

    this._blip({ freq: 300 + Math.random() * 80, type: 'triangle', dur: 0.05, gain: 0.22, at: t });
  }

  /**
   * "Oof!" — a brother grunting when he's hit. Plays one of the 23 recorded
   * grunts at random, as a region of the sprite buffer: Web Audio's
   * `start(when, offset, duration)` plays a sub-range of a buffer directly, so
   * no slicing is needed and all 23 share one decode.
   *
   * Two touches keep repeated hits from sounding like a stuck record: the same
   * grunt never plays twice in a row, and each is nudged slightly in pitch. No-op
   * until the sprite has loaded (see {@link _loadOofs}) or if audio is locked.
   *
   * @param {number} [gain]  Level, 0..1. Defaults to `Config.audio.oofGain`;
   *   pass a lower value for a softer hit.
   * @returns {void}
   */
  oof(gain = Config.audio.oofGain) {
    if (!this._ctx || !this._oofs) return;
    const ctx = this._ctx;
    const t = ctx.currentTime;

    // Retrigger guard (Config.audio.oofRetriggerMs): one grunt per collision
    // "event". A second brother hit inside this window is the same bump as far
    // as the ear is concerned, and stacking half-second voices sounds broken.
    if (t - this._lastOofAt < Config.audio.oofRetriggerMs / 1000) return;
    this._lastOofAt = t;

    // Pick a grunt, but never the one we just played: true randomness repeats
    // often enough to sound like a bug (23 clips still means a ~4% repeat rate).
    let i = Math.floor(Math.random() * OOF_CLIPS.length);
    if (i === this._lastOof) i = (i + 1) % OOF_CLIPS.length;
    this._lastOof = i;
    const [offset, duration] = OOF_CLIPS[i];

    const src = ctx.createBufferSource();
    src.buffer = this._oofs;
    // +/- 6% pitch. Enough to vary a repeat, small enough that the voice still
    // sounds like the same brother rather than a chipmunk.
    src.playbackRate.value = 0.94 + Math.random() * 0.12;

    const g = ctx.createGain();
    g.gain.value = Math.max(0, Math.min(1, gain));
    src.connect(g).connect(/** @type {GainNode} */ (this._master));

    // Three-arg start: play just this region of the sprite. Nothing is sliced.
    src.start(t, offset, duration);
  }

  /**
   * Explosion: a lowpass noise "boom" whose cutoff sweeps down as it decays,
   * plus a low sine thump for body — the cue when a bomb strikes a brother.
   *
   * @returns {void}
   */
  explode() {
    if (!this._ctx) return;
    const ctx = this._ctx;
    const t = ctx.currentTime;
    const dur = 0.5;

    // A longer noise buffer than the click's, cached separately.
    if (!this._boomNoise) {
      const len = Math.ceil(ctx.sampleRate * 0.6);
      this._boomNoise = ctx.createBuffer(1, len, ctx.sampleRate);
      const d = this._boomNoise.getChannelData(0);
      for (let i = 0; i < len; i++) d[i] = Math.random() * 2 - 1;
    }
    const src = ctx.createBufferSource();
    src.buffer = this._boomNoise;
    const lp = ctx.createBiquadFilter();
    lp.type = 'lowpass';
    lp.frequency.setValueAtTime(1800, t);
    lp.frequency.exponentialRampToValueAtTime(120, t + dur);
    const g = ctx.createGain();
    g.gain.setValueAtTime(0.9, t);
    g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
    src.connect(lp).connect(g).connect(/** @type {GainNode} */ (this._master));
    src.start(t);
    src.stop(t + dur);

    // Low body thump gliding down under the boom.
    this._blip({ freq: 90, glideTo: 30, dur: 0.4, type: 'sine', gain: 0.5, at: t });
  }

  /**
   * Bonk: a short, comic two-tone downward "boink" — played when a modal pops up
   * to flag an unusual request/situation. Deliberately distinct from the ball
   * click and the win/lose cues.
   *
   * @returns {void}
   */
  bonk() {
    if (!this._ctx) return;
    const t = this._ctx.currentTime;
    this._blip({ freq: 420, glideTo: 90, dur: 0.2, type: 'triangle', gain: 0.5, at: t });
    this._blip({ freq: 210, glideTo: 60, dur: 0.22, type: 'sine', gain: 0.28, at: t });
  }

  /**
   * A soft, short UI click for menu taps and toggles — quieter and higher than
   * {@link hit}, and distinct from the modal {@link bonk}.
   *
   * @returns {void}
   */
  tick() {
    if (!this._ctx) return;
    // Schedule a hair in the future, not exactly at currentTime: this blip is very
    // short, and scheduling at currentTime can land a render quantum in the past,
    // clipping the attack so the tick intermittently goes silent. A small lookahead
    // (and a slightly longer/louder blip) makes it fire reliably.
    this._blip({ freq: 1200, type: 'triangle', dur: 0.05, gain: 0.22, at: this._ctx.currentTime + 0.02 });
  }

  /**
   * Grab: a soft, short high "tick" when the launcher is picked up. Deliberately
   * a clean tonal pip (no noise), so it's clearly not the {@link hit} ball-click.
   *
   * @returns {void}
   */
  grab() {
    if (!this._ctx) return;
    const t = this._ctx.currentTime;
    // A crisp high pip with a lower-octave body under it, so it's clearly
    // audible over the scene yet still a clean tone (not the noisy ball-click).
    this._blip({ freq: 1046, type: 'triangle', dur: 0.05, gain: 0.5, at: t });
    this._blip({ freq: 523, type: 'sine', dur: 0.05, gain: 0.28, at: t });
  }

  /**
   * Teleport: a quick upward pitch sweep ("vwoop") — the classic warp cue. A
   * triangle lead with a sine an octave below for body, both gliding up fast.
   *
   * @returns {void}
   */
  teleport() {
    if (!this._ctx) return;
    const t = this._ctx.currentTime;
    this._blip({ freq: 180, glideTo: 1500, dur: 0.26, type: 'triangle', gain: 0.3, at: t });
    this._blip({ freq: 90, glideTo: 750, dur: 0.26, type: 'sine', gain: 0.16, at: t });
  }

  /**
   * Success: a quick rising major arpeggio (C5–E5–G5–C6) with a sparkle on
   * top — a bright, triumphant flourish.
   *
   * @returns {void}
   */
  win() {
    if (!this._ctx) return;
    const t = this._ctx.currentTime;
    const notes = [523.25, 659.25, 783.99, 1046.5];
    notes.forEach((f, i) =>
      this._blip({ freq: f, type: 'triangle', dur: 0.5 - i * 0.04, gain: 0.3, at: t + i * 0.11 })
    );
    this._blip({ freq: 1568, type: 'sine', dur: 0.4, gain: 0.14, at: t + 0.33 });
  }

  /**
   * Failure: two soft, lowpass-filtered tones bending downward — a sad little
   * "wah-wah" that reads as "awww".
   *
   * @returns {void}
   */
  lose() {
    if (!this._ctx) return;
    const t = this._ctx.currentTime;
    this._wah(220, 165, t, 0.32);
    this._wah(175, 110, t + 0.3, 0.5);
  }

  /**
   * Begin the "stretching rubber band" sound, held until {@link stopBand}. A
   * cartoon-rubber FM voice (see rubber-band-simulator.html): a triangle
   * *carrier* (hollow, elastic body) is frequency-modulated by a detuned
   * sawtooth *modulator* for rubbery grit, then shaped by a resonant lowpass —
   * the hollow "balloon squelch". The voice is built once and left running
   * silently (see {@link _ensureBand}); this just activates the gate, so no nodes
   * are added to a live graph. {@link updateBand} then drives pitch from tension
   * and volume from how fast the draw length is changing, so a held stretch falls
   * silent and can never hum. No-op if audio isn't unlocked yet.
   *
   * @returns {void}
   */
  startBand() {
    this._ensureBand(); // usually already built in _warmup; build on demand if not
    if (!this._band) return;
    const b = this._band;
    b.active = true;
    b.lastK = 0; // fresh stretch: reset the rate-of-change tracking
    b.lastT = /** @type {AudioContext} */ (this._ctx).currentTime;
  }

  /**
   * Drive the rubber-band FM voice from the *current* draw tension. Call this
   * every frame while aiming (not only when the pointer moves), so a held draw
   * decays to silence. Pitch (and FM depth / filter brightness) rise with
   * tension; loudness tracks the rate of length change — it only makes noise
   * while stretching or relaxing. No-op if no band is playing.
   *
   * @param {number} tension  0 (slack) .. 1 (fully drawn).
   * @returns {void}
   */
  updateBand(tension) {
    if (!this._band || !this._band.active || !this._ctx) return;
    const k = Math.max(0, Math.min(1, tension));
    const now = this._ctx.currentTime;
    const b = this._band;
    const ramp = (param, v, tc = 0.02) => param.setTargetAtTime(v, now, tc);

    // Rate of length change since the last frame; only this makes sound.
    const dt = Math.max(1e-3, now - b.lastT);
    const activity = Math.min(1, (Math.abs(k - b.lastK) / dt) * 0.35);
    b.lastK = k;
    b.lastT = now;

    // Synth parameters mirror the reference simulator. Tension stands in for the
    // simulator's pull distance via a nominal stretch span, so the same pitch /
    // FM-depth math applies. (basePitch 85, pitchBend 2.5, modRatio 1.4,
    // modScale 10, filterQ 1.)
    const stretch = k * 280; // nominal pull distance in "px"
    const pitch = 85 + stretch * 2.5; // ~85..785 Hz as tension rises
    const modDepth = stretch * (10 / 100) * (pitch * 0.1); // FM depth (grit)

    ramp(b.carrier.frequency, pitch);
    ramp(b.modulator.frequency, pitch * 1.4);
    ramp(b.modGain.gain, modDepth);
    ramp(b.filter.frequency, pitch * 2.5, 0.03); // brighter as it scales out
    ramp(b.filter.Q, 1);
    // Velocity -> amplitude. Capped so fast yanks don't blow out the mix.
    ramp(b.g.gain, Math.min(0.21, activity * 0.4), 0.01);
  }

  /**
   * Stop the rubber-band sound with a short fade so a release doesn't click.
   *
   * @returns {void}
   */
  stopBand() {
    if (!this._band || !this._ctx) return;
    const b = this._band;
    const now = this._ctx.currentTime;
    // Fade the gate to silence; leave the graph running (see _ensureBand). The
    // oscillators keep going at zero output, so nothing is removed from the graph.
    b.g.gain.cancelScheduledValues(now);
    b.g.gain.setTargetAtTime(0.0001, now, 0.03);
    b.active = false;
  }

  /**
   * One downward-gliding, lowpass-softened "wah" tone for {@link lose}.
   *
   * @param {number} from  Start frequency (Hz).
   * @param {number} to    End frequency (Hz).
   * @param {number} at    Start time (AudioContext seconds).
   * @param {number} dur   Duration (s).
   * @returns {void}
   */
  _wah(from, to, at, dur) {
    const ctx = /** @type {AudioContext} */ (this._ctx);
    const osc = ctx.createOscillator();
    const lp = ctx.createBiquadFilter();
    const g = ctx.createGain();
    lp.type = 'lowpass';
    lp.frequency.value = 900;
    osc.type = 'sawtooth';
    osc.frequency.setValueAtTime(from, at);
    osc.frequency.exponentialRampToValueAtTime(to, at + dur);
    g.gain.setValueAtTime(0.0001, at);
    g.gain.exponentialRampToValueAtTime(0.3, at + 0.05);
    g.gain.exponentialRampToValueAtTime(0.0001, at + dur);
    osc.connect(lp).connect(g).connect(/** @type {GainNode} */ (this._master));
    osc.start(at);
    osc.stop(at + dur + 0.02);
  }
}

/** Shared instance: one AudioContext for the whole game, reused across restarts. */
export const sfx = new Sfx();
